name: cinemapedia_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^9.0.3
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/loaders/logo.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#42a5f5"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
